# Generated by Django 2.1.7 on 2019-10-26 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firm_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firm_name', to='data.Company', verbose_name='Название'),
            preserve_default=False,
        ),
    ]
