# Generated by Django 2.2.6 on 2019-10-28 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('data', '0001_initial'),
        ('auth_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='firm_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firm_name', to='data.Company', verbose_name='Название'),
        ),
    ]
