# Generated by Django 2.1.7 on 2019-10-26 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth_core', '0002_auto_20191026_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='firm_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='firm_name', to='data.Company', verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.IntegerField(blank=True, choices=[(1, 'Прораб'), (2, 'Суб подрядчик'), (3, 'Ген подрядчик'), (4, 'Завод')], null=True, verbose_name='Статус сотрудника'),
        ),
    ]
